[package]
name = "backstage-template-creator"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2.14"
clap = "3.2.11"
env_logger = "0.9.0"
log = "0.4.17"
walkdir = "2.3.2"
wax = "0.5.0"
